name: Static Code Analysis
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  workflow_dispatch:
  
defaults:
  - name: suiteName
    displayName: 'Test suite'
    type: string
    default: 'CRITICAL_PATH'
    values:
      - 'SANITY'
      - 'CRITICAL_PATH'
      - 'REGRESSION'
   
