name: Set ENV
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      env:
        description: Select ENV
        required: true
        type: choice
        options:
          - dev
          - uat
          - prod
      language:
        description: Select Language
        required: true
        type: choice
        options:
          - ua
          - en
          - ar
jobs:
  tests:
    name: Check ENV
    runs-on: ubuntu-latest
    steps:
      - name: Set Name
        run: echo "Eto est ${{ github.event.inputs.env }}"
          
