name: Static Code Analysis
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  workflow_dispatch:

jobs:

  spotless-analyser-check:
    name: SPOTLESS Static Code Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17
      - name: SPOTLESS Static Code Analysis
        run: mvn spotless:check

  pmd-analyser-check:
    needs: spotless-analyser-check
    name: PMD Static Code Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17
      - name: PMD Static Code Analysis
        run: mvn pmd:check
      - name: No PMD Errors?
        if: steps.pmd.outputs.violations != 0
        run: exit 1
