name: PMD Static Code Analysis
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  pmd-analyser-checkk:
    name: PMD Static Code Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Get FrameWork
      - uses: actions/checkout@v3

      - name: SetUp Java-17
      - uses: actions/setup-java@v3
        with:
          java-version: 17
      - name: Start PMD Static Code Analysis
      - uses: pmd/pmd-github-action@v1
        with:
          version: '6.40.0'
          #sourcePath: 'src/main/java'
          rulesets: 'rules/maven-pmd-plugin-custom-rules.xml'
  
      - name: No PMD Errors?
        if: steps.pmd.outputs.violations != 0
        run: exit 1
