name: PMD Static Code Analysis
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  pmd-analyser-check:
    name: PMD Static Code Analysis
    permissions:
      security-events: write
      actions: read
      contents: read
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'
    - uses: pmd/pmd-github-action@v1
      id: pmd
      with:
        version: '6.40.0'       
        sourcePath: 'src/main/java'
        rulesets: 'rules/maven-pmd-plugin-custom-rules.xml'
        error-rules: 'AvoidDirectAccessTriggerMap,AvoidDmlStatementsInLoops,AvoidHardcodingId'
        note-rules: 'ApexDoc'
    - name: No PMD Errors?
      if: steps.pmd.outputs.violations != 0
      run: exit 1      
