name: PMD Static Code Analysis
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  pmd-analyser-checkk:
    name: PMD Static Code Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
          
      - name: PMD Check Start
        run: mvn pmd:check   
        
      - name: No PMD Errors?
        if: steps.pmd.outputs.violations != 0
        run: exit 1
